# Generated by Django 4.0.1 on 2022-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_rename_task_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
